### ISSUE TITLE
Absolute paths not supported in `Location` header

### ISSUE THREAD

**Issue by jautor** [DMTF/libredfish#156]
`Location` header should allow for either relative or absolute paths, including scheme `http://` or `https://`

**Comment by edtanous** [comment]
Having a Location header be an absolute path has a lot of problems in implementations:

- The output of the request might be flushed through a Redfish aggregator, which would need to both detect this case, and handle all possible corner cases of using an ip address instead of a hostname, using a local hosts file name in the uri, as well as the host having multiple well known DNS names.

- The output of the request might run through a "dumb" reverse proxy (think nginx or similar) that would result in the source seemingly having a different source name. If location contains an absolute path, this reverse proxy now has to have significant smarts in it, when a naive reverse proxy is desired.

- For restful create semantics, for which Location is used generally, it's not clear that an absolute URI is valid or preferred, even though it is technically allowed in the HTTP RFC. For a given RESTful service, the CRUD operation is being performed on a restful implementation on that particular service. Returning an absolute path to a Location implies that the resource could've been created outside of this REST resource tree, which in a RESTful interface wouldn't be a create action, it would be something else entirely, because it wouldn't be effecting this services tree.

**Comment by mraineri** [comment]
Closing; not going forward with the change
